# Use a base image with the necessary dependencies
FROM mcr.microsoft.com/vscode/devcontainers/base:bullseye

# Install Terraform
RUN apt-get update && \
    apt-get install -y ca-certificates curl wget && \
    wget https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip && \
    unzip terraform_1.3.9_linux_amd64.zip && \
    mv terraform /usr/local/bin/ && \
    rm terraform_1.3.9_linux_amd64.zip