name: Deploy Workflow 1

on:
  workflow_dispatch: # Trigger on manual run

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Secret Access
        run: |
          echo "Checking if secrets are accessible..."
          if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "AZURE_CREDENTIALS is not set."
          else
            echo "AZURE_CREDENTIALS is set."
          fi
      
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      - name: Retrieve the Container Registry login server
        run: echo "ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)" >> $GITHUB_ENV
      
      - name: Retrieve ACR Credentials
        run: |
          ACR_CREDENTIALS=$(az acr credential show --name "$(terraform output -raw acr_name)" --resource-group "$(terraform output -raw resource_group_name)")
          ACR_USERNAME=$(echo $ACR_CREDENTIALS | jq -r '.username')
          ACR_PASSWORD=$(echo $ACR_CREDENTIALS | jq -r '.passwords[0].value')
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV
      
      - name: Log into the Container Registry
        run: az acr login --name "$(terraform output -raw acr_name)"
      
      - name: Build and push the Docker image
        run: |
          cd timeentrydenjs2
          docker build -t $ACR_LOGIN_SERVER/timeentrydenext:latest .
          docker push $ACR_LOGIN_SERVER/timeentrydenext:latest
      
      - name: Configure the Web App to use the Docker image
        run: |
          az webapp config container set \
            --name "$(terraform output -raw web_app_name)" \
            --resource-group "$(terraform output -raw resource_group_name)" \
            --docker-registry-server-url "https://$ACR_LOGIN_SERVER" \
            --docker-registry-server-user "$ACR_USERNAME" \
            --docker-registry-server-password "$ACR_PASSWORD" \
            --docker-custom-image-name "$ACR_LOGIN_SERVER/timeentrydenext:latest"
